### PR TITLE
feat: refactored the package structure

### PR DESCRIPTION
**Pull request by Fersoil**
refactored the following package structure:
```
src/meteors
|
|-attr/...
|-visualize/...
|-utils
|   |-models/...
|   |-utils.py
|-exceptions/...
|-hsi.py
```
into
```
src/meteors
|
|-attr/...
|-visualize/...
|-models/...
|-exceptions.py
|-utils.py
|-hsi.py
```

additionally adjusted tests and test directory

### CODE REVIEW

**Comment by WolodjaZ** [comment]
For consideration @Fersoil maybe we should change where needed typing from list  or tuple to Iterable like that:
`
from collections.abc import Iterable
from typing import TypeVar, Union, overload

Number = TypeVar('Number', int, float)

def process_iterator(data: Iterable[Number]) -> list[Number]:
`

If this idea is fine then it should be implemented in this PR.

**Comment by Fersoil** [comment]
> For consideration @Fersoil maybe we should change where needed typing from list or tuple to Iterable like that: ` from collections.abc import Iterable from typing import TypeVar, Union, overload
> 
> Number = TypeVar('Number', int, float)
> 
> def process_iterator(data: Iterable[Number]) -> list[Number]: `
> 
> If this idea is fine then it should be implemented in this PR.


Well, that's a good idea, but I think it is not a significant update. In fact, it could make our code a little more transparent, but I don't really feel like this change is worth implementing at this stage of the project.

Another problem that I see is with the Iterable type - for lists and tuples, we are referring sometimes to an element - Iterable does not support that.

**Comment by Fersoil** [comment]
> Yes but then we can specify for example int | Iterabla[int] and not int | list[int] | tuple[int]. Because sometimes user will provide a tuple as a list but we should change only to accept list as it is more likely that user provide it even if we ask about tuple.

I don't really get what you mean here. Do you want to tell that users will more often pass lists instead of tuples?

**Comment by WolodjaZ** [comment]
Yep, I am afraid that we should switch to list or use iterable and always convert to list because probably some users will not see the difference and list is more popular.

**Comment by Fersoil** [comment]
So why shouldn't we keep it as it is now? If it turns out that the tuple is unnecessary, we might remove it from typing

**Pull request merged**
