### PR TITLE
docs: refine the example for segmentation problem type

### PR DESCRIPTION
**Pull request by Fersoil**
added a tutorial for segmentation problem type

### CODE REVIEW

**Comment by WolodjaZ** [comment]
Merge 15,16 and 17 cells into one.

**Comment by Fersoil** [comment]
> * Merge 15,16 and 17 cells into one.

why exactly should I merge the cells?

> * Use patch segmentation instead of `slic`

Use it along the `slic` segmentation or instead?

**Comment by WolodjaZ** [comment]
I mean there are cells that show the shape before and after aggregation per cell, we can do everything in one cell and at the end show before and after aggregation shape—just it.

instead of slic, I think it will be much better.

**Comment by Fersoil** [comment]
> I mean there are cells that show the shape before and after aggregation per cell, we can do everything in one cell and at the end show before and after aggregation shape—just it.
> 

Well, I think that there is no need to merge them. For me, in each of the cells a separate thing is being done. Particularly in the cells 16 and 17, where model is initialized and later the attributions are calculated - those two things should be separated I guess.

I would remove then the cell 15 or merge it into 14 then.

> instead of slic, I think it will be much better.

I rerun the examples with larger number of steps, and the results turned out to be very nice:
image

**Review by WolodjaZ — APPROVED** [review]

**Pull request merged**
